print("I am Learning Git")
print("Hello From Roshaan")
print("This is my Feature Branch")
print("I am Learning Git")
print("Hello From Master ")
print("Hello from conflcit test")
print("This is my Feature Branch")
add =5+6
print (add)
print("This is my test feature")
print("Login feature placeholder")
